from heuristic.useOpenStreetMap import *
from heuristic.expandBlocks import *
from heuristic.deleteIsolated import *
from heuristic.deleteIsolatedGroups import *
from heuristic.join import *
from heuristic.mergeColors import *
from heuristic.addBuilding import *
from heuristic.createWalls import *
from heuristic.useOpenStreetMap import *
from heuristic.setGreenZone import *
from heuristic.setRoads import *
